version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - my_server
      - id_server
      - my_frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - my_server
      - id_server
      - my_frontend

  my_frontend:
    image: tkhenghong/maybankpoc-reactjs:my-latest
    container_name: my_frontend
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - '3002:80'
    environment:
      - BACKEND_URI=http://my_server:3000
    networks:
      - app-network

  my_server:
    image: tkhenghong/mbbpoc-node-express:my-latest
    container_name: my_server
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - APP_NAME=Maybank Heart Malaysia From Docker Compose
      - APP_ID=MY
      - MONGODB_URI=mongodb://mongo:27017/mh
    networks:
      - app-network

  id_server:
    image: tkhenghong/mbbpoc-node-express:id-latest
    container_name: id_server
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - APP_NAME=Maybank Heart Indonesia From Docker Compose
      - APP_ID=ID
      - MONGODB_URI=mongodb://mongo:27017/mh
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
#    driver: bridge
    external: true
