version: '3'

services:
  my_server:
    image: tkhenghong/maybankheartpoc:my-latest
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - '3001:3000'
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - APP_NAME=Maybank Heart Malaysia
      - APP_ID=MY
      - MONGODB_URI=mongodb://mongo:27017/mh

  id_server:
    image: tkhenghong/maybankheartpoc:id-latest
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - APP_NAME=Maybank Heart Indonesia
      - APP_ID=ID
      - MONGODB_URI=mongodb://mongo:27017/mh

  mongo:
    image: mongo
    container_name: "mongo"
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
volumes:
  db: