version: "2"

services:

  server:
    image: tkhenghong/mbb-h:latest
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - APP_NAME='Maybank Heart Malaysia'
      - MONGO_URI='mongodb://mongo:27017/mh'

  mongo:
    image: mongo
    ports:
      - "27017:27017"
