version: "2"

services:
  my_server:
    image: tkhenghong/maybankheartpoc:my-latest
    volumes:
      - ./:/app
    ports:
      - "3001:3000"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - APP_NAME='Maybank Heart Malaysia'
      - APP_ID='MY'
      - MONGO_URI='mongodb://mongo:27017/mh'

  id_server:
    image: tkhenghong/maybankheartpoc:id-latest
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - APP_NAME='Maybank Heart Indonesia'
      - APP_ID='ID'
      - MONGO_URI='mongodb://mongo:27017/mh'

  mongo:
    image: mongo
    ports:
      - "27017:27017"
